### ISSUE TITLE
Out of Memory while trying to train the model

### ISSUE THREAD

**Issue by ujwaljp** [Legal-NLP-EkStep/legal_NER#6]
I have been trying to retrain the model using the config.cfg and data available in the repo using the training command given in the repo. But always this error occurs-
```Token indices sequence length is longer than the specified maximum sequence length for this model (514 > 512). Running this sequence through the model will result in indexing errors
⚠ Aborting and saving the final best model. Encountered exception:
OutOfMemoryError('CUDA out of memory. Tried to allocate 144.00 MiB (GPU 0; 3.81
GiB total capacity; 2.75 GiB already allocated; 81.12 MiB free; 2.79 GiB
reserved in total by PyTorch) If reserved memory is >> allocated memory try
setting max_split_size_mb to avoid fragmentation.  See documentation for Memory
Management and PYTORCH_CUDA_ALLOC_CONF')
Traceback (most recent call last):
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/spacy/__main__.py", line 4, in <module>
    setup_cli()
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/spacy/cli/_util.py", line 74, in setup_cli
    command(prog_name=COMMAND)
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/spacy/cli/train.py", line 45, in train_cli
    train(config_path, output_path, use_gpu=use_gpu, overrides=overrides)
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/spacy/cli/train.py", line 75, in train
    train_nlp(nlp, output_path, use_gpu=use_gpu, stdout=sys.stdout, stderr=sys.stderr)
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/spacy/training/loop.py", line 124, in train
    raise e
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/spacy/training/loop.py", line 107, in train
    for batch, info, is_best_checkpoint in training_step_iterator:
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/spacy/training/loop.py", line 209, in train_while_improving
    nlp.update(
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/spacy/language.py", line 1155, in update
    proc.update(examples, sgd=None, losses=losses, **component_cfg[name])  # type: ignore
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/spacy_transformers/pipeline_component.py", line 294, in update
    trf_full, bp_trf_full = self.model.begin_update(docs)
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/thinc/model.py", line 309, in begin_update
    return self._func(self, X, is_train=True)
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/spacy_transformers/layers/transformer_model.py", line 199, in forward
    model_output, bp_tensors = transformer(wordpieces, is_train)
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/thinc/model.py", line 291, in __call__
    return self._func(self, X, is_train=is_train)
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/thinc/layers/pytorchwrapper.py", line 219, in forward
    Ytorch, torch_backprop = model.shims[0](Xtorch, is_train)
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/thinc/shims/pytorch.py", line 90, in __call__
    return self.begin_update(inputs)
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/thinc/shims/pytorch.py", line 124, in begin_update
    output = self._model(*inputs.args, **inputs.kwargs)
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/transformers/models/roberta/modeling_roberta.py", line 851, in forward
    encoder_outputs = self.encoder(
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/transformers/models/roberta/modeling_roberta.py", line 526, in forward
    layer_outputs = layer_module(
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/transformers/models/roberta/modeling_roberta.py", line 411, in forward
    self_attention_outputs = self.attention(
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/transformers/models/roberta/modeling_roberta.py", line 338, in forward
    self_outputs = self.self(
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/transformers/models/roberta/modeling_roberta.py", line 268, in forward
    attention_probs = self.dropout(attention_probs)
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/torch/nn/modules/dropout.py", line 59, in forward
    return F.dropout(input, self.p, self.training, self.inplace)
  File "/home/ujwal/miniconda3/envs/ugp/lib/python3.8/site-packages/torch/nn/functional.py", line 1252, in dropout
    return _VF.dropout_(input, p, training) if inplace else _VF.dropout(input, p, training)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 144.00 MiB (GPU 0; 3.81 GiB total capacity; 2.75 GiB already allocated; 81.12 MiB free; 2.79 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
. I have also tried using colab, but still this error occurs. How do I resolve this?

**Comment by abhigyan631** [comment]
Hi,
  Any updates on this issue, please? Thank you.

**Comment by prathameshk** [comment]
It seems you will need a bigger gpu to train this model if reducing batch size is not working.

**Comment by amant555** [comment]
@abhigyan631 Some of the sentences in data set are very big. You can filter some out and use a GPU such as T4 to train the model. Otherwise you can train it on a much bigger GPU's. Hope this helps!!
